plugins:
  duplication:
    enabled: true
    config:
      languages:
        go:
          mass_threshold: 140
  gofmt:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
