version: "2"

checks:
  # Go idiomatically has many return statements, one for each error check
  # more error checking is obviously a good thing
  return-statements:
    enabled: false

plugins:
  duplication:
    enabled: true
    config:
      languages:
        go:
          mass_threshold: 140
  gofmt:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
