name: Main workflow
on: [push]
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@master
      - name: Setup Go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.1'
      - name: Unit Tests
        run: make test
